"""Add networks table for ground truth

Revision ID: 235edad9591d
Revises: 5534a95a041d
Create Date: 2026-09-04 22:55:13.606546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '235edad9591d'
down_revision: Union[str, Sequence[str], None] = '5534a95a041d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_entities',
    sa.Column('network_id', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('network_id', 'entity_id')
    )
    op.create_index(op.f('ix_network_entities_entity_id'), 'network_entities', ['entity_id'], unique=False)
    op.create_index(op.f('ix_network_entities_network_id'), 'network_entities', ['network_id'], unique=False)
    op.create_table('networks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scenario_type', sa.String(), nullable=False),
    sa.Column('is_abuse', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_networks_id'), 'networks', ['id'], unique=False)
    op.create_index(op.f('ix_networks_scenario_type'), 'networks', ['scenario_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_networks_scenario_type'), table_name='networks')
    op.drop_index(op.f('ix_networks_id'), table_name='networks')
    op.drop_table('networks')
    op.drop_index(op.f('ix_network_entities_network_id'), table_name='network_entities')
    op.drop_index(op.f('ix_network_entities_entity_id'), table_name='network_entities')
    op.drop_table('network_entities')
    # ### end Alembic commands ###
