"""Init

Revision ID: 5534a95a041d
Revises: 
Create Date: 2026-09-04 22:33:56.937855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5534a95a041d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_value', sa.String(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('is_synthetic', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_entity_type'), 'entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entities_entity_value'), 'entities', ['entity_value'], unique=False)
    op.create_index(op.f('ix_entities_id'), 'entities', ['id'], unique=False)
    op.create_table('edges',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_entity_id', sa.String(), nullable=True),
    sa.Column('target_entity_id', sa.String(), nullable=True),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edges_id'), 'edges', ['id'], unique=False)
    op.create_index(op.f('ix_edges_relationship_type'), 'edges', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_edges_source_entity_id'), 'edges', ['source_entity_id'], unique=False)
    op.create_index(op.f('ix_edges_target_entity_id'), 'edges', ['target_entity_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('merchant_id', sa.String(), nullable=True),
    sa.Column('payment_instrument_id', sa.String(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('ip_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_abuse', sa.Boolean(), nullable=True),
    sa.Column('network_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['ip_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['payment_instrument_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_customer_id'), 'transactions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_transactions_device_id'), 'transactions', ['device_id'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_ip_id'), 'transactions', ['ip_id'], unique=False)
    op.create_index(op.f('ix_transactions_merchant_id'), 'transactions', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_transactions_network_id'), 'transactions', ['network_id'], unique=False)
    op.create_index(op.f('ix_transactions_payment_instrument_id'), 'transactions', ['payment_instrument_id'], unique=False)
    op.create_index(op.f('ix_transactions_timestamp'), 'transactions', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_timestamp'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_payment_instrument_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_network_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_merchant_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_ip_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_device_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_customer_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_edges_target_entity_id'), table_name='edges')
    op.drop_index(op.f('ix_edges_source_entity_id'), table_name='edges')
    op.drop_index(op.f('ix_edges_relationship_type'), table_name='edges')
    op.drop_index(op.f('ix_edges_id'), table_name='edges')
    op.drop_table('edges')
    op.drop_index(op.f('ix_entities_id'), table_name='entities')
    op.drop_index(op.f('ix_entities_entity_value'), table_name='entities')
    op.drop_index(op.f('ix_entities_entity_type'), table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
